
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 20 12:54:33 BRT 2014
//----------------------------------------------------

package com.analizador.var;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 3;
  public static final int VAR = 2;
  public static final int error = 1;
  public static final int SEPARADOR = 6;
  public static final int TIPO_VARIAVEL = 4;
  public static final int ADD_ATTR_VAR = 5;
  public static final int EOF = 0;
}

