
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 20 21:54:45 BRT 2014
//----------------------------------------------------

package com.analizador.algoritmoName;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ID = 3;
  public static final int STRING = 4;
  public static final int error = 1;
  public static final int ALGORITMO = 2;
  public static final int EOF = 0;
}

