
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Sep 26 15:47:26 BRT 2014
//----------------------------------------------------

package com.compilador.portugol;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int FIMALGORITMO = 52;
  public static final int COSSENO = 34;
  public static final int TIPO_VARIAVEL_VETOR = 5;
  public static final int FUNCAO = 38;
  public static final int CASO = 26;
  public static final int DE = 43;
  public static final int FIMSE = 19;
  public static final int FIMENQUANTO = 23;
  public static final int CHAR = 59;
  public static final int ESCREVAL = 50;
  public static final int ESCOLHA = 25;
  public static final int PI = 37;
  public static final int CONDICIONAL_NUMERICA = 41;
  public static final int SE = 16;
  public static final int ATRIBUIR = 10;
  public static final int CONDICIONAL_COMPARATIVA = 42;
  public static final int SEPARADOR = 54;
  public static final int DOIS_PONTOS = 15;
  public static final int PASSO = 46;
  public static final int E = 44;
  public static final int OUTROCASO = 27;
  public static final int OPERADOR_SOMA = 8;
  public static final int OU = 47;
  public static final int ATE = 45;
  public static final int RAIZ = 36;
  public static final int ENTAO = 17;
  public static final int VALOR_LOGICO = 9;
  public static final int ALGORITMO = 2;
  public static final int ID = 55;
  public static final int ADD_ATTR_VAR = 53;
  public static final int EOF = 0;
  public static final int NUMERO_INT = 57;
  public static final int error = 1;
  public static final int SENAO = 18;
  public static final int ENQUANTO = 20;
  public static final int FECHAR_COLCHETE = 14;
  public static final int ABRIR_PARENTESE = 11;
  public static final int MODULO = 32;
  public static final int ESCREVA = 49;
  public static final int VOID = 40;
  public static final int FIMPARA = 24;
  public static final int FACA = 22;
  public static final int TIPO_VARIAVEL = 4;
  public static final int POTENCIA = 31;
  public static final int FECHAR_PARENTESE = 12;
  public static final int LEIA = 51;
  public static final int TANGENTE = 35;
  public static final int OPERADOR = 7;
  public static final int INTERROMPA = 29;
  public static final int FIMESCOLHA = 28;
  public static final int SENO = 33;
  public static final int FIMFUNCAO = 39;
  public static final int STRING = 56;
  public static final int ESPERAR = 30;
  public static final int PARA = 21;
  public static final int INICIO = 6;
  public static final int NAO = 48;
  public static final int NUMERO_FLOAT = 58;
  public static final int VAR = 3;
  public static final int ABRIR_COLCHETE = 13;
}

