
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Jun 20 14:14:23 BRT 2014
//----------------------------------------------------

package com.analizador.exe_expressao;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUS = 4;
  public static final int DIVIDE = 6;
  public static final int UMINUS = 8;
  public static final int NUMBER = 11;
  public static final int MOD = 7;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final int PLUS = 3;
  public static final int error = 1;
  public static final int RPAREN = 10;
  public static final int TIMES = 5;
  public static final int LPAREN = 9;
}

