
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 21 09:26:22 BRT 2014
//----------------------------------------------------

package com.analizador.expressao;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR = 3;
  public static final int ABRIR_PARENTESE = 4;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int NUMERO = 6;
  public static final int ID = 7;
  public static final int error = 1;
  public static final int FECHAR_PARENTESE = 5;
  public static final int ATRIBUIR = 2;
}

