
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jun 24 15:37:09 BRT 2014
//----------------------------------------------------

package com.analizador.exp_condicional;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR = 7;
  public static final int SE = 2;
  public static final int CONDICIONAL_ESPECIAL = 5;
  public static final int CONDICIONAL_ADITIVA = 6;
  public static final int ABRIR_PARENTESE = 8;
  public static final int STRING = 12;
  public static final int EOF = 0;
  public static final int NUMERO = 10;
  public static final int ID = 11;
  public static final int CONDICIONAL = 4;
  public static final int error = 1;
  public static final int FECHAR_PARENTESE = 9;
  public static final int ENTAO = 3;
}

