
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Jun 26 11:55:25 BRT 2014
//----------------------------------------------------

package com.analizador.separadorLoop;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPERADOR = 6;
  public static final int ABRIR_PARENTESE = 4;
  public static final int STRING = 8;
  public static final int EOF = 0;
  public static final int NUMERO = 9;
  public static final int SEPARADOR = 3;
  public static final int ID = 7;
  public static final int error = 1;
  public static final int FECHAR_PARENTESE = 5;
  public static final int ESCREVA = 2;
}

